// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb2DJmUtI36BICt42J2hwQh2s_ixyoBqE',
    appId: '1:181367002981:web:07bd13ea3e1d0352f8f38c',
    messagingSenderId: '181367002981',
    projectId: 'dummy-ecom-app',
    authDomain: 'dummy-ecom-app.firebaseapp.com',
    storageBucket: 'dummy-ecom-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoi06vJP0B1Va15Kwg-lWtHFzrwhThQqA',
    appId: '1:181367002981:android:310f53650ec3c10df8f38c',
    messagingSenderId: '181367002981',
    projectId: 'dummy-ecom-app',
    storageBucket: 'dummy-ecom-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZfOXW8rZiNFpgcO-jffQHxXFTj95aEXg',
    appId: '1:181367002981:ios:db3774ddd3dfd427f8f38c',
    messagingSenderId: '181367002981',
    projectId: 'dummy-ecom-app',
    storageBucket: 'dummy-ecom-app.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZfOXW8rZiNFpgcO-jffQHxXFTj95aEXg',
    appId: '1:181367002981:ios:225268b0bad8a0d6f8f38c',
    messagingSenderId: '181367002981',
    projectId: 'dummy-ecom-app',
    storageBucket: 'dummy-ecom-app.appspot.com',
    iosBundleId: 'com.example.ecomApp.RunnerTests',
  );
}
